#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Net-INET6Glue
Version  : 0.603
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/S/SU/SULLR/Net-INET6Glue-0.603.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/S/SU/SULLR/Net-INET6Glue-0.603.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libn/libnet-inet6glue-perl/libnet-inet6glue-perl_0.603-2.debian.tar.xz
Summary  : unknown
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Net-INET6Glue-license
Requires: perl-Net-INET6Glue-man

%description
Net::INET6Glue is a hack to make more of Perl IPv6 able.
This is partly done by replacing IO::Socket::INET with IO::Socket::INET6
and by adding IPv6 Protocol functionality to Net::FTP.
Works for Net::SMTP, LWP, Net::FTP and probably others too.

%package license
Summary: license components for the perl-Net-INET6Glue package.
Group: Default

%description license
license components for the perl-Net-INET6Glue package.


%package man
Summary: man components for the perl-Net-INET6Glue package.
Group: Default

%description man
man components for the perl-Net-INET6Glue package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Net-INET6Glue-0.603
mkdir -p %{_topdir}/BUILD/Net-INET6Glue-0.603/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Net-INET6Glue-0.603/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Net-INET6Glue
cp COPYRIGHT %{buildroot}/usr/share/doc/perl-Net-INET6Glue/COPYRIGHT
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Net/INET6Glue.pm
/usr/lib/perl5/site_perl/5.26.1/Net/INET6Glue/FTP.pm
/usr/lib/perl5/site_perl/5.26.1/Net/INET6Glue/INET_is_INET6.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Net-INET6Glue/COPYRIGHT

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Net::INET6Glue.3
/usr/share/man/man3/Net::INET6Glue::FTP.3
/usr/share/man/man3/Net::INET6Glue::INET_is_INET6.3
